name: CI/CD Deploy to K8s

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > ${{ github.workspace }}/kubeconfig
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: Set up Helm
      uses: azure/setup-helm@v3
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig

    - name: Deploy using Helm
      run: |
        helm upgrade flask-prod ./flask-chart \
          --install \
          --namespace default \
          --create-namespace \
          --set image.tag=${{ github.sha }}
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig
