name: CI/CD Deploy to Kind (CI Testing)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Kubernetes cluster with Kind
      uses: helm/kind-action@v1
      with:
        cluster_name: kind-ci

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy with Helm
      run: |
        helm upgrade --install flask-prod ./flask-chart \
          --namespace default \
          --create-namespace \
          --set image.tag=${{ github.sha }}
